#:schema node_modules/wrangler/config-schema.json
name = "warp-vips-ztlist"
main = "src/index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
STORE_R2 = true
R2_INPUT_DEVICES_FILENAME = "warp_vips.json"
R2_INPUT_GROUPS_FILENAME = "okta_groups.json"
GROUPS = ["engineering","finance","marketing","contractors","research"]
R2_OUTPUT_FILENAMES = "warp_vips_" # the filenames will be warp_vips_<groupname>.json

[triggers]
crons = ["*/6 * * * *"] # run every 6 minutes

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "warp-vips"